### ISSUE TITLE
Use ggcall with patchwork

### ISSUE THREAD

**Issue by igrave** [Polkas/ggcall#7]
Thanks for the cool tool. I'm wondering if we could combine this functionality with patchwork. I guess they are also overwriting the arithmetic operators.

**Comment by Polkas** [comment]
Great comment, thanks for your contribution.

I already have a branch with a working solution https://github.com/Polkas/ggcall/pull/8/files

- The current solution has to be improved and well-tested
- I always wanted ggcall to be a light solution, but now it is growing. I have to think about it and if we can make patchwork support optional and easy to exclude if not needed.

**Comment by Polkas** [comment]
Now the patchwork operators are supported.
The functionality will be formally added in the next released, but you can access it when using main branch (currently with 9000 suffix).

**Comment by gravesti** [comment]
Thanks @Polkas !
Check this out @BFalquet

**Comment by Polkas** [comment]
I plan to make a first CRAN release of ggcall this week.
One more thank you for a great suggestion:)
